"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

fibonacci = [1, 2]

n1 = 1
n2 = 2

while n2 <= 4000000:
  new_number = n1 + n2
  fibonacci.append(new_number)
  n1 = n2
  n2 = new_number

even_total = 0

for number in fibonacci:
   if number % 2 == 0:
      even_total += number
     
print(even_total)
